//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegracaoPagador.PagadorQuery {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery", ConfigurationName="PagadorQuery.PagadorQuerySoap")]
    public interface PagadorQuerySoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.pagador.com.br/query/pagadorquery/GetOrderData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractRequest))]
        IntegracaoPagador.PagadorQuery.OrderDataResponse GetOrderData(IntegracaoPagador.PagadorQuery.OrderDataRequest orderDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.pagador.com.br/query/pagadorquery/GetOrderData", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegracaoPagador.PagadorQuery.OrderDataResponse> GetOrderDataAsync(IntegracaoPagador.PagadorQuery.OrderDataRequest orderDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.pagador.com.br/query/pagadorquery/GetTransactionData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractRequest))]
        IntegracaoPagador.PagadorQuery.TransactionDataResponse GetTransactionData(IntegracaoPagador.PagadorQuery.TransactionDataRequest transactionDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.pagador.com.br/query/pagadorquery/GetTransactionData", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegracaoPagador.PagadorQuery.TransactionDataResponse> GetTransactionDataAsync(IntegracaoPagador.PagadorQuery.TransactionDataRequest transactionDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.pagador.com.br/query/pagadorquery/GetCustomerData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractRequest))]
        IntegracaoPagador.PagadorQuery.CustomerDataResponse GetCustomerData(IntegracaoPagador.PagadorQuery.CustomerDataRequest customerDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.pagador.com.br/query/pagadorquery/GetCustomerData", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegracaoPagador.PagadorQuery.CustomerDataResponse> GetCustomerDataAsync(IntegracaoPagador.PagadorQuery.CustomerDataRequest customerDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.pagador.com.br/query/pagadorquery/GetCreditCardData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractRequest))]
        IntegracaoPagador.PagadorQuery.CreditCardDataResponse GetCreditCardData(IntegracaoPagador.PagadorQuery.CreditCardDataRequest creditCardDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.pagador.com.br/query/pagadorquery/GetCreditCardData", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegracaoPagador.PagadorQuery.CreditCardDataResponse> GetCreditCardDataAsync(IntegracaoPagador.PagadorQuery.CreditCardDataRequest creditCardDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.pagador.com.br/query/pagadorquery/GetAdditionalData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractRequest))]
        IntegracaoPagador.PagadorQuery.AdditionalDataResponse GetAdditionalData(IntegracaoPagador.PagadorQuery.AdditionalDataRequest additionalDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.pagador.com.br/query/pagadorquery/GetAdditionalData", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegracaoPagador.PagadorQuery.AdditionalDataResponse> GetAdditionalDataAsync(IntegracaoPagador.PagadorQuery.AdditionalDataRequest additionalDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.pagador.com.br/query/pagadorquery/GetDeliveryAddressData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractRequest))]
        IntegracaoPagador.PagadorQuery.DeliveryAddressDataResponse GetDeliveryAddressData(IntegracaoPagador.PagadorQuery.DeliveryAddressDataRequest addressDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.pagador.com.br/query/pagadorquery/GetDeliveryAddressData", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegracaoPagador.PagadorQuery.DeliveryAddressDataResponse> GetDeliveryAddressDataAsync(IntegracaoPagador.PagadorQuery.DeliveryAddressDataRequest addressDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.pagador.com.br/query/pagadorquery/GetBoletoData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractRequest))]
        IntegracaoPagador.PagadorQuery.BoletoDataResponse GetBoletoData(IntegracaoPagador.PagadorQuery.BoletoDataRequest boletoDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.pagador.com.br/query/pagadorquery/GetBoletoData", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegracaoPagador.PagadorQuery.BoletoDataResponse> GetBoletoDataAsync(IntegracaoPagador.PagadorQuery.BoletoDataRequest boletoDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.pagador.com.br/query/pagadorquery/GetBraspagOrderId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractRequest))]
        IntegracaoPagador.PagadorQuery.BraspagOrderIdDataResponse GetBraspagOrderId(IntegracaoPagador.PagadorQuery.BraspagOrderIdDataRequest braspagOrderIdDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.pagador.com.br/query/pagadorquery/GetBraspagOrderId", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegracaoPagador.PagadorQuery.BraspagOrderIdDataResponse> GetBraspagOrderIdAsync(IntegracaoPagador.PagadorQuery.BraspagOrderIdDataRequest braspagOrderIdDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.pagador.com.br/query/pagadorquery/GetOrderIdData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractRequest))]
        IntegracaoPagador.PagadorQuery.OrderIdDataResponse GetOrderIdData(IntegracaoPagador.PagadorQuery.OrderIdDataRequest orderIdDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.pagador.com.br/query/pagadorquery/GetOrderIdData", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegracaoPagador.PagadorQuery.OrderIdDataResponse> GetOrderIdDataAsync(IntegracaoPagador.PagadorQuery.OrderIdDataRequest orderIdDataRequest);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class OrderDataRequest : AbstractRequest {
        
        private System.Guid merchantIdField;
        
        private System.Guid braspagOrderIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid MerchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("MerchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid BraspagOrderId {
            get {
                return this.braspagOrderIdField;
            }
            set {
                this.braspagOrderIdField = value;
                this.RaisePropertyChanged("BraspagOrderId");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderIdDataRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BraspagOrderIdDataRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BoletoDataRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeliveryAddressDataRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdditionalDataRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreditCardDataRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomerDataRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransactionDataRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderDataRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public abstract partial class AbstractRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid requestIdField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class Refund : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long amountField;
        
        private byte statusField;
        
        private string reasonField;
        
        private string receivedDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public byte Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ReceivedDate {
            get {
                return this.receivedDateField;
            }
            set {
                this.receivedDateField = value;
                this.RaisePropertyChanged("ReceivedDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class RejectReason : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ruleIdField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int RuleId {
            get {
                return this.ruleIdField;
            }
            set {
                this.ruleIdField = value;
                this.RaisePropertyChanged("RuleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class VelocityAnalysis : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private string resultMessageField;
        
        private int scoreField;
        
        private RejectReason[] rejectReasonsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ResultMessage {
            get {
                return this.resultMessageField;
            }
            set {
                this.resultMessageField = value;
                this.RaisePropertyChanged("ResultMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
                this.RaisePropertyChanged("Score");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public RejectReason[] RejectReasons {
            get {
                return this.rejectReasonsField;
            }
            set {
                this.rejectReasonsField = value;
                this.RaisePropertyChanged("RejectReasons");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class OrderTransactionDataResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid braspagTransactionIdField;
        
        private string orderIdField;
        
        private string acquirerTransactionIdField;
        
        private short paymentMethodField;
        
        private string paymentMethodNameField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private long amountField;
        
        private string authorizationCodeField;
        
        private short numberOfPaymentsField;
        
        private string currencyField;
        
        private string countryField;
        
        private System.Nullable<byte> transactionTypeField;
        
        private byte statusField;
        
        private string receivedDateField;
        
        private string capturedDateField;
        
        private string voidedDateField;
        
        private System.Nullable<System.Guid> creditCardTokenField;
        
        private string proofOfSaleField;
        
        private string maskedCardNumberField;
        
        private string capturedAmountField;
        
        private string voidedAmountField;
        
        private string ipAddressField;
        
        private VelocityAnalysis velocityAnalysisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid BraspagTransactionId {
            get {
                return this.braspagTransactionIdField;
            }
            set {
                this.braspagTransactionIdField = value;
                this.RaisePropertyChanged("BraspagTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("OrderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AcquirerTransactionId {
            get {
                return this.acquirerTransactionIdField;
            }
            set {
                this.acquirerTransactionIdField = value;
                this.RaisePropertyChanged("AcquirerTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public short PaymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                this.paymentMethodField = value;
                this.RaisePropertyChanged("PaymentMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PaymentMethodName {
            get {
                return this.paymentMethodNameField;
            }
            set {
                this.paymentMethodNameField = value;
                this.RaisePropertyChanged("PaymentMethodName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AuthorizationCode {
            get {
                return this.authorizationCodeField;
            }
            set {
                this.authorizationCodeField = value;
                this.RaisePropertyChanged("AuthorizationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public short NumberOfPayments {
            get {
                return this.numberOfPaymentsField;
            }
            set {
                this.numberOfPaymentsField = value;
                this.RaisePropertyChanged("NumberOfPayments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<byte> TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
                this.RaisePropertyChanged("TransactionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public byte Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ReceivedDate {
            get {
                return this.receivedDateField;
            }
            set {
                this.receivedDateField = value;
                this.RaisePropertyChanged("ReceivedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CapturedDate {
            get {
                return this.capturedDateField;
            }
            set {
                this.capturedDateField = value;
                this.RaisePropertyChanged("CapturedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string VoidedDate {
            get {
                return this.voidedDateField;
            }
            set {
                this.voidedDateField = value;
                this.RaisePropertyChanged("VoidedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<System.Guid> CreditCardToken {
            get {
                return this.creditCardTokenField;
            }
            set {
                this.creditCardTokenField = value;
                this.RaisePropertyChanged("CreditCardToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ProofOfSale {
            get {
                return this.proofOfSaleField;
            }
            set {
                this.proofOfSaleField = value;
                this.RaisePropertyChanged("ProofOfSale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string MaskedCardNumber {
            get {
                return this.maskedCardNumberField;
            }
            set {
                this.maskedCardNumberField = value;
                this.RaisePropertyChanged("MaskedCardNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string CapturedAmount {
            get {
                return this.capturedAmountField;
            }
            set {
                this.capturedAmountField = value;
                this.RaisePropertyChanged("CapturedAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string VoidedAmount {
            get {
                return this.voidedAmountField;
            }
            set {
                this.voidedAmountField = value;
                this.RaisePropertyChanged("VoidedAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string IpAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
                this.RaisePropertyChanged("IpAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public VelocityAnalysis VelocityAnalysis {
            get {
                return this.velocityAnalysisField;
            }
            set {
                this.velocityAnalysisField = value;
                this.RaisePropertyChanged("VelocityAnalysis");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class ErrorReportDataResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderIdTransactionResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderIdDataResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BraspagOrderIdDataResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BoletoDataResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeliveryAddressDataResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdditionalTransactionDataResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdditionalDataResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreditCardDataResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomerDataResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransactionDataResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderDataResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public abstract partial class AbstractResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid correlationIdField;
        
        private bool successField;
        
        private ErrorReportDataResponse[] errorReportDataCollectionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid CorrelationId {
            get {
                return this.correlationIdField;
            }
            set {
                this.correlationIdField = value;
                this.RaisePropertyChanged("CorrelationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public ErrorReportDataResponse[] ErrorReportDataCollection {
            get {
                return this.errorReportDataCollectionField;
            }
            set {
                this.errorReportDataCollectionField = value;
                this.RaisePropertyChanged("ErrorReportDataCollection");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class OrderIdTransactionResponse : AbstractResponse {
        
        private System.Guid braspagOrderIdField;
        
        private System.Guid[] braspagTransactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid BraspagOrderId {
            get {
                return this.braspagOrderIdField;
            }
            set {
                this.braspagOrderIdField = value;
                this.RaisePropertyChanged("BraspagOrderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public System.Guid[] BraspagTransactionId {
            get {
                return this.braspagTransactionIdField;
            }
            set {
                this.braspagTransactionIdField = value;
                this.RaisePropertyChanged("BraspagTransactionId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class OrderIdDataResponse : AbstractResponse {
        
        private OrderIdTransactionResponse[] orderIdDataCollectionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public OrderIdTransactionResponse[] OrderIdDataCollection {
            get {
                return this.orderIdDataCollectionField;
            }
            set {
                this.orderIdDataCollectionField = value;
                this.RaisePropertyChanged("OrderIdDataCollection");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class BraspagOrderIdDataResponse : AbstractResponse {
        
        private System.Nullable<System.Guid> braspagOrderIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.Guid> BraspagOrderId {
            get {
                return this.braspagOrderIdField;
            }
            set {
                this.braspagOrderIdField = value;
                this.RaisePropertyChanged("BraspagOrderId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class BoletoDataResponse : AbstractResponse {
        
        private System.Guid braspagTransactionIdField;
        
        private short paymentMethodField;
        
        private string documentNumberField;
        
        private string documentDateField;
        
        private string customerNameField;
        
        private string boletoNumberField;
        
        private string barCodeNumberField;
        
        private string boletoExpirationDateField;
        
        private string boletoInstructionsField;
        
        private string boletoTypeField;
        
        private string boletoUrlField;
        
        private long amountField;
        
        private long paidAmountField;
        
        private string paymentDateField;
        
        private string bankNumberField;
        
        private string agencyField;
        
        private string accountField;
        
        private string assignorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid BraspagTransactionId {
            get {
                return this.braspagTransactionIdField;
            }
            set {
                this.braspagTransactionIdField = value;
                this.RaisePropertyChanged("BraspagTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short PaymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                this.paymentMethodField = value;
                this.RaisePropertyChanged("PaymentMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DocumentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
                this.RaisePropertyChanged("DocumentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocumentDate {
            get {
                return this.documentDateField;
            }
            set {
                this.documentDateField = value;
                this.RaisePropertyChanged("DocumentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
                this.RaisePropertyChanged("CustomerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BoletoNumber {
            get {
                return this.boletoNumberField;
            }
            set {
                this.boletoNumberField = value;
                this.RaisePropertyChanged("BoletoNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string BarCodeNumber {
            get {
                return this.barCodeNumberField;
            }
            set {
                this.barCodeNumberField = value;
                this.RaisePropertyChanged("BarCodeNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string BoletoExpirationDate {
            get {
                return this.boletoExpirationDateField;
            }
            set {
                this.boletoExpirationDateField = value;
                this.RaisePropertyChanged("BoletoExpirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string BoletoInstructions {
            get {
                return this.boletoInstructionsField;
            }
            set {
                this.boletoInstructionsField = value;
                this.RaisePropertyChanged("BoletoInstructions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string BoletoType {
            get {
                return this.boletoTypeField;
            }
            set {
                this.boletoTypeField = value;
                this.RaisePropertyChanged("BoletoType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string BoletoUrl {
            get {
                return this.boletoUrlField;
            }
            set {
                this.boletoUrlField = value;
                this.RaisePropertyChanged("BoletoUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public long Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public long PaidAmount {
            get {
                return this.paidAmountField;
            }
            set {
                this.paidAmountField = value;
                this.RaisePropertyChanged("PaidAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string PaymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
                this.RaisePropertyChanged("PaymentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string BankNumber {
            get {
                return this.bankNumberField;
            }
            set {
                this.bankNumberField = value;
                this.RaisePropertyChanged("BankNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Agency {
            get {
                return this.agencyField;
            }
            set {
                this.agencyField = value;
                this.RaisePropertyChanged("Agency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("Account");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Assignor {
            get {
                return this.assignorField;
            }
            set {
                this.assignorField = value;
                this.RaisePropertyChanged("Assignor");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class DeliveryAddressDataResponse : AbstractResponse {
        
        private string streetField;
        
        private string numberField;
        
        private string complementField;
        
        private string districtField;
        
        private string zipCodeField;
        
        private string cityField;
        
        private string stateField;
        
        private string countryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Complement {
            get {
                return this.complementField;
            }
            set {
                this.complementField = value;
                this.RaisePropertyChanged("Complement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
                this.RaisePropertyChanged("District");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("ZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class AdditionalTransactionDataResponse : AbstractResponse {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class AdditionalDataResponse : AbstractResponse {
        
        private AdditionalTransactionDataResponse[] additionalDataCollectionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public AdditionalTransactionDataResponse[] AdditionalDataCollection {
            get {
                return this.additionalDataCollectionField;
            }
            set {
                this.additionalDataCollectionField = value;
                this.RaisePropertyChanged("AdditionalDataCollection");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class CreditCardDataResponse : AbstractResponse {
        
        private string cardHolderField;
        
        private string cardNumberField;
        
        private string cardExpirationDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CardHolder {
            get {
                return this.cardHolderField;
            }
            set {
                this.cardHolderField = value;
                this.RaisePropertyChanged("CardHolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
                this.RaisePropertyChanged("CardNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CardExpirationDate {
            get {
                return this.cardExpirationDateField;
            }
            set {
                this.cardExpirationDateField = value;
                this.RaisePropertyChanged("CardExpirationDate");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class CustomerDataResponse : AbstractResponse {
        
        private string customerIdentityField;
        
        private string customerNameField;
        
        private string customerEmailField;
        
        private string streetField;
        
        private string numberField;
        
        private string complementField;
        
        private string districtField;
        
        private string zipCodeField;
        
        private string cityField;
        
        private string stateField;
        
        private string countryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerIdentity {
            get {
                return this.customerIdentityField;
            }
            set {
                this.customerIdentityField = value;
                this.RaisePropertyChanged("CustomerIdentity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
                this.RaisePropertyChanged("CustomerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CustomerEmail {
            get {
                return this.customerEmailField;
            }
            set {
                this.customerEmailField = value;
                this.RaisePropertyChanged("CustomerEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Complement {
            get {
                return this.complementField;
            }
            set {
                this.complementField = value;
                this.RaisePropertyChanged("Complement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
                this.RaisePropertyChanged("District");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("ZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class TransactionDataResponse : AbstractResponse {
        
        private System.Guid braspagTransactionIdField;
        
        private string orderIdField;
        
        private string acquirerTransactionIdField;
        
        private short paymentMethodField;
        
        private string paymentMethodNameField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private long amountField;
        
        private string authorizationCodeField;
        
        private short numberOfPaymentsField;
        
        private string currencyField;
        
        private string countryField;
        
        private System.Nullable<byte> transactionTypeField;
        
        private byte statusField;
        
        private string receivedDateField;
        
        private string capturedDateField;
        
        private string voidedDateField;
        
        private System.Nullable<System.Guid> creditCardTokenField;
        
        private string proofOfSaleField;
        
        private string maskedCardNumberField;
        
        private string capturedAmountField;
        
        private string voidedAmountField;
        
        private string voidReasonField;
        
        private string ipAddressField;
        
        private VelocityAnalysis velocityAnalysisField;
        
        private Refund[] refundsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid BraspagTransactionId {
            get {
                return this.braspagTransactionIdField;
            }
            set {
                this.braspagTransactionIdField = value;
                this.RaisePropertyChanged("BraspagTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("OrderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AcquirerTransactionId {
            get {
                return this.acquirerTransactionIdField;
            }
            set {
                this.acquirerTransactionIdField = value;
                this.RaisePropertyChanged("AcquirerTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public short PaymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                this.paymentMethodField = value;
                this.RaisePropertyChanged("PaymentMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PaymentMethodName {
            get {
                return this.paymentMethodNameField;
            }
            set {
                this.paymentMethodNameField = value;
                this.RaisePropertyChanged("PaymentMethodName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AuthorizationCode {
            get {
                return this.authorizationCodeField;
            }
            set {
                this.authorizationCodeField = value;
                this.RaisePropertyChanged("AuthorizationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public short NumberOfPayments {
            get {
                return this.numberOfPaymentsField;
            }
            set {
                this.numberOfPaymentsField = value;
                this.RaisePropertyChanged("NumberOfPayments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<byte> TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
                this.RaisePropertyChanged("TransactionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public byte Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ReceivedDate {
            get {
                return this.receivedDateField;
            }
            set {
                this.receivedDateField = value;
                this.RaisePropertyChanged("ReceivedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CapturedDate {
            get {
                return this.capturedDateField;
            }
            set {
                this.capturedDateField = value;
                this.RaisePropertyChanged("CapturedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string VoidedDate {
            get {
                return this.voidedDateField;
            }
            set {
                this.voidedDateField = value;
                this.RaisePropertyChanged("VoidedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<System.Guid> CreditCardToken {
            get {
                return this.creditCardTokenField;
            }
            set {
                this.creditCardTokenField = value;
                this.RaisePropertyChanged("CreditCardToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ProofOfSale {
            get {
                return this.proofOfSaleField;
            }
            set {
                this.proofOfSaleField = value;
                this.RaisePropertyChanged("ProofOfSale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string MaskedCardNumber {
            get {
                return this.maskedCardNumberField;
            }
            set {
                this.maskedCardNumberField = value;
                this.RaisePropertyChanged("MaskedCardNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string CapturedAmount {
            get {
                return this.capturedAmountField;
            }
            set {
                this.capturedAmountField = value;
                this.RaisePropertyChanged("CapturedAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string VoidedAmount {
            get {
                return this.voidedAmountField;
            }
            set {
                this.voidedAmountField = value;
                this.RaisePropertyChanged("VoidedAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string VoidReason {
            get {
                return this.voidReasonField;
            }
            set {
                this.voidReasonField = value;
                this.RaisePropertyChanged("VoidReason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string IpAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
                this.RaisePropertyChanged("IpAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public VelocityAnalysis VelocityAnalysis {
            get {
                return this.velocityAnalysisField;
            }
            set {
                this.velocityAnalysisField = value;
                this.RaisePropertyChanged("VelocityAnalysis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=25)]
        public Refund[] Refunds {
            get {
                return this.refundsField;
            }
            set {
                this.refundsField = value;
                this.RaisePropertyChanged("Refunds");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class OrderDataResponse : AbstractResponse {
        
        private OrderTransactionDataResponse[] transactionDataCollectionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public OrderTransactionDataResponse[] TransactionDataCollection {
            get {
                return this.transactionDataCollectionField;
            }
            set {
                this.transactionDataCollectionField = value;
                this.RaisePropertyChanged("TransactionDataCollection");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class OrderIdDataRequest : AbstractRequest {
        
        private System.Guid merchantIdField;
        
        private string orderIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid MerchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("MerchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("OrderId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class BraspagOrderIdDataRequest : AbstractRequest {
        
        private System.Guid merchantIdField;
        
        private System.Guid braspagTransactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid MerchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("MerchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid BraspagTransactionId {
            get {
                return this.braspagTransactionIdField;
            }
            set {
                this.braspagTransactionIdField = value;
                this.RaisePropertyChanged("BraspagTransactionId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class BoletoDataRequest : AbstractRequest {
        
        private System.Guid merchantIdField;
        
        private System.Guid braspagTransactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid MerchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("MerchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid BraspagTransactionId {
            get {
                return this.braspagTransactionIdField;
            }
            set {
                this.braspagTransactionIdField = value;
                this.RaisePropertyChanged("BraspagTransactionId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class DeliveryAddressDataRequest : AbstractRequest {
        
        private System.Guid merchantIdField;
        
        private System.Guid braspagOrderIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid MerchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("MerchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid BraspagOrderId {
            get {
                return this.braspagOrderIdField;
            }
            set {
                this.braspagOrderIdField = value;
                this.RaisePropertyChanged("BraspagOrderId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class AdditionalDataRequest : AbstractRequest {
        
        private System.Guid merchantIdField;
        
        private System.Guid braspagTransactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid MerchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("MerchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid BraspagTransactionId {
            get {
                return this.braspagTransactionIdField;
            }
            set {
                this.braspagTransactionIdField = value;
                this.RaisePropertyChanged("BraspagTransactionId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class CreditCardDataRequest : AbstractRequest {
        
        private System.Guid merchantIdField;
        
        private System.Guid braspagTransactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid MerchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("MerchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid BraspagTransactionId {
            get {
                return this.braspagTransactionIdField;
            }
            set {
                this.braspagTransactionIdField = value;
                this.RaisePropertyChanged("BraspagTransactionId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class CustomerDataRequest : AbstractRequest {
        
        private System.Guid merchantIdField;
        
        private System.Guid braspagOrderIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid MerchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("MerchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid BraspagOrderId {
            get {
                return this.braspagOrderIdField;
            }
            set {
                this.braspagOrderIdField = value;
                this.RaisePropertyChanged("BraspagOrderId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.pagador.com.br/query/pagadorquery")]
    public partial class TransactionDataRequest : AbstractRequest {
        
        private System.Guid merchantIdField;
        
        private System.Guid braspagTransactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid MerchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("MerchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid BraspagTransactionId {
            get {
                return this.braspagTransactionIdField;
            }
            set {
                this.braspagTransactionIdField = value;
                this.RaisePropertyChanged("BraspagTransactionId");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PagadorQuerySoapChannel : IntegracaoPagador.PagadorQuery.PagadorQuerySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PagadorQuerySoapClient : System.ServiceModel.ClientBase<IntegracaoPagador.PagadorQuery.PagadorQuerySoap>, IntegracaoPagador.PagadorQuery.PagadorQuerySoap {
        
        public PagadorQuerySoapClient() {
        }
        
        public PagadorQuerySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PagadorQuerySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagadorQuerySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagadorQuerySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IntegracaoPagador.PagadorQuery.OrderDataResponse GetOrderData(IntegracaoPagador.PagadorQuery.OrderDataRequest orderDataRequest) {
            return base.Channel.GetOrderData(orderDataRequest);
        }
        
        public System.Threading.Tasks.Task<IntegracaoPagador.PagadorQuery.OrderDataResponse> GetOrderDataAsync(IntegracaoPagador.PagadorQuery.OrderDataRequest orderDataRequest) {
            return base.Channel.GetOrderDataAsync(orderDataRequest);
        }
        
        public IntegracaoPagador.PagadorQuery.TransactionDataResponse GetTransactionData(IntegracaoPagador.PagadorQuery.TransactionDataRequest transactionDataRequest) {
            return base.Channel.GetTransactionData(transactionDataRequest);
        }
        
        public System.Threading.Tasks.Task<IntegracaoPagador.PagadorQuery.TransactionDataResponse> GetTransactionDataAsync(IntegracaoPagador.PagadorQuery.TransactionDataRequest transactionDataRequest) {
            return base.Channel.GetTransactionDataAsync(transactionDataRequest);
        }
        
        public IntegracaoPagador.PagadorQuery.CustomerDataResponse GetCustomerData(IntegracaoPagador.PagadorQuery.CustomerDataRequest customerDataRequest) {
            return base.Channel.GetCustomerData(customerDataRequest);
        }
        
        public System.Threading.Tasks.Task<IntegracaoPagador.PagadorQuery.CustomerDataResponse> GetCustomerDataAsync(IntegracaoPagador.PagadorQuery.CustomerDataRequest customerDataRequest) {
            return base.Channel.GetCustomerDataAsync(customerDataRequest);
        }
        
        public IntegracaoPagador.PagadorQuery.CreditCardDataResponse GetCreditCardData(IntegracaoPagador.PagadorQuery.CreditCardDataRequest creditCardDataRequest) {
            return base.Channel.GetCreditCardData(creditCardDataRequest);
        }
        
        public System.Threading.Tasks.Task<IntegracaoPagador.PagadorQuery.CreditCardDataResponse> GetCreditCardDataAsync(IntegracaoPagador.PagadorQuery.CreditCardDataRequest creditCardDataRequest) {
            return base.Channel.GetCreditCardDataAsync(creditCardDataRequest);
        }
        
        public IntegracaoPagador.PagadorQuery.AdditionalDataResponse GetAdditionalData(IntegracaoPagador.PagadorQuery.AdditionalDataRequest additionalDataRequest) {
            return base.Channel.GetAdditionalData(additionalDataRequest);
        }
        
        public System.Threading.Tasks.Task<IntegracaoPagador.PagadorQuery.AdditionalDataResponse> GetAdditionalDataAsync(IntegracaoPagador.PagadorQuery.AdditionalDataRequest additionalDataRequest) {
            return base.Channel.GetAdditionalDataAsync(additionalDataRequest);
        }
        
        public IntegracaoPagador.PagadorQuery.DeliveryAddressDataResponse GetDeliveryAddressData(IntegracaoPagador.PagadorQuery.DeliveryAddressDataRequest addressDataRequest) {
            return base.Channel.GetDeliveryAddressData(addressDataRequest);
        }
        
        public System.Threading.Tasks.Task<IntegracaoPagador.PagadorQuery.DeliveryAddressDataResponse> GetDeliveryAddressDataAsync(IntegracaoPagador.PagadorQuery.DeliveryAddressDataRequest addressDataRequest) {
            return base.Channel.GetDeliveryAddressDataAsync(addressDataRequest);
        }
        
        public IntegracaoPagador.PagadorQuery.BoletoDataResponse GetBoletoData(IntegracaoPagador.PagadorQuery.BoletoDataRequest boletoDataRequest) {
            return base.Channel.GetBoletoData(boletoDataRequest);
        }
        
        public System.Threading.Tasks.Task<IntegracaoPagador.PagadorQuery.BoletoDataResponse> GetBoletoDataAsync(IntegracaoPagador.PagadorQuery.BoletoDataRequest boletoDataRequest) {
            return base.Channel.GetBoletoDataAsync(boletoDataRequest);
        }
        
        public IntegracaoPagador.PagadorQuery.BraspagOrderIdDataResponse GetBraspagOrderId(IntegracaoPagador.PagadorQuery.BraspagOrderIdDataRequest braspagOrderIdDataRequest) {
            return base.Channel.GetBraspagOrderId(braspagOrderIdDataRequest);
        }
        
        public System.Threading.Tasks.Task<IntegracaoPagador.PagadorQuery.BraspagOrderIdDataResponse> GetBraspagOrderIdAsync(IntegracaoPagador.PagadorQuery.BraspagOrderIdDataRequest braspagOrderIdDataRequest) {
            return base.Channel.GetBraspagOrderIdAsync(braspagOrderIdDataRequest);
        }
        
        public IntegracaoPagador.PagadorQuery.OrderIdDataResponse GetOrderIdData(IntegracaoPagador.PagadorQuery.OrderIdDataRequest orderIdDataRequest) {
            return base.Channel.GetOrderIdData(orderIdDataRequest);
        }
        
        public System.Threading.Tasks.Task<IntegracaoPagador.PagadorQuery.OrderIdDataResponse> GetOrderIdDataAsync(IntegracaoPagador.PagadorQuery.OrderIdDataRequest orderIdDataRequest) {
            return base.Channel.GetOrderIdDataAsync(orderIdDataRequest);
        }
    }
}
